# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e57914ee64c064a438e22688fd7f835c8fd39959158aeeee5628cc54730fe0b40e436657cf26f55e2780c83b722b3e0c83bc55e903a23a5330f6c4acc84a00c7

test:
  secret_key_base: 756c00ce8c46504672998ad7426cf3fa3f87df1210f2b127ebbfc06e41805ad42f63b731252bf6c88d4fe90eb7a08f378a31a56f0969afd972c67be148f7b36c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
